eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8888
spring:
  application:
    name: ServiceConsumer

feign:
  hystrix:
    enabled: true

ribbon:
  ReadTimeout: 45000
  MaxAutoRetriesNextServe: 0
  MaxAutoRetries: 2

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
